"""Seller advice computed from real data, not generated by the LLM.

- price_plan: three list prices from comparable current listings and their units
  sold. Prices are still ASKING prices; the Browse API has no sold-price history.
- title_checks: which of the details buyers search by are in the title.
"""

import math
import re
from statistics import quantiles

from app.pricing import comparable_items, weighted_median
from app.title_format import title_specifics

MAX_TITLE_CHECKS = 6


def charm(price: float) -> float:
    """$239.40 -> $238.99: the familiar .99 ending, never above the computed price."""
    return round(math.floor(price) - 0.01, 2) if price >= 10 else round(price, 2)


def price_plan(items: list[dict], condition: str | None) -> dict:
    """Sell fast (P25), recommended (sales-weighted median, kept inside P25-P75) and
    max (P75), plus how many of the units sold were listed at or below recommended."""
    same = comparable_items(items, condition)
    if len(same) < 4:
        return {}
    p25, _, p75 = quantiles([i["price"] for i in same], n=4)
    weighted = weighted_median([i["price"] for i in same], [1 + (i.get("sold_quantity") or 0) for i in same])
    recommended = min(max(weighted, p25), p75)
    sold = [(i["price"], i["sold_quantity"]) for i in same if i.get("sold_quantity")]
    return {
        "currency": same[0].get("currency"),
        "fast": charm(p25),
        "recommended": charm(recommended),
        "max": charm(p75),
        "units_sold": sum(q for _, q in sold),
        "units_sold_at_or_below_recommended": sum(q for p, q in sold if p <= recommended),
        "listings": len(same),
    }


def _squash(text: str) -> str:
    return re.sub(r"[^a-z0-9]", "", text.lower())


def title_checks(group: str, title: str, specifics: dict[str, str], missing_required: list[str]) -> list[dict]:
    """Known search details (in title priority order) with whether the title has them,
    then eBay-required details that are still unknown (value None)."""
    squashed = _squash(title)
    checks = [
        {"aspect": name, "value": value, "in_title": _squash(value) in squashed}
        for name, value in title_specifics(group, specifics).items()
    ]
    checks += [{"aspect": name, "value": None, "in_title": False} for name in missing_required]
    return checks[:MAX_TITLE_CHECKS]
